### ISSUE TITLE
Add group: sign to glass/plastic signs

### ISSUE THREAD

**Issue by parnikkapore** [mt-mods/basic_signs#1]
The current obsidian glass and plastic signs are not in the `sign` group, which causes latest signs_lib to crash when attempting to refresh those signs.

Probably the more correct way to do this is to force-add anything created by `signs_lib.register_sign` to the `sign` group.

**Comment by parnikkapore** [comment]
This is what such a crash would look like:

```plain
stack traceback:
	/home/user/.minetest/mods/signs_lib/api.lua:245: in function 'spawn_entity'
	/home/user/.minetest/mods/signs_lib/api.lua:268: in function 'set_obj_text'
	/home/user/.minetest/mods/signs_lib/api.lua:802: in function 'update_sign'
	/home/user/.minetest/mods/signs_lib/api.lua:1181: in function </home/user/.minetest/mods/signs_lib/api.lua:1180>
```

**Comment by fluxionary** [comment]
I think this should be fixed by forcing anything registered via `signs_lib:register_sign` into the sign group.
