### ISSUE TITLE
unknown steel:sheet_metal?

### ISSUE THREAD

**Issue by waxtatect** [mt-mods/basic_signs#4]
https://github.com/mt-mods/basic_signs/blob/master/crafting.lua#L24

8 recipes are using "steel:sheet_metal", where could it be registered?
- steel mod isn't in mod.conf depends
- this item isn't defined in https://github.com/mt-mods/steel

perhaps a replacement for steel:sheet_metal?

**Comment by Niklp09** [comment]
I didn't found "steel:sheet_metal" in an advanced github search
https://github.com/search?l=&p=1&q=steel%3Asheet_metal&type=Code

**Comment by SwissalpS** [comment]
craftitem is registered here, still no recipe though
https://github.com/Cryterion/CrytSurvival/blob/70a397e47b4eb3f39f032ee3f269a29e303486aa/mods/steel/init.lua#L149
